[build]
  base    = "peppercloud_formbuilder_frontend"
  publish = "build"
  command = "npm install --force --legacy-peer-deps && npm run build"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
